### ISSUE TITLE
add example .env file as Mine does not work (Got attached one..)

### ISSUE THREAD

**Issue by 1ntroduc3** [jessejputnam/card-collector#14]
Can you help me out with an example env file maybe?

This is mine:

MONGODB_URI="mongodb+srv://server:password@cluster0.sv6v9lq.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
SESSION_SECRET=dlalalallalalla123
POKE_API_KEY=4817990c-4c66-2bCz3-b472-2ae2dd41f870

This ".env" file does not seem to work:

` node app.jsa
express-session deprecated req.secret; provide secret option app.js:84:3
(node:26576) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\connection.js:695
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at Connection.openUri (C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\connection.js:695:11)
    at C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\index.js:414:10
    at C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\index.js:1290:10)
    at Mongoose.connect (C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\index.js:413:20)
    at Object.<anonymous> (C:\Users\marth\Downloads\card-collector-main\app.js:22:10)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.9.0
PS C:\Users\marth\Downloads\card-collector-main>
PS C:\Users\marth\Downloads\card-collector-main> `

**Comment by jessejputnam** [comment]
Drop the double quotes in your MONGODB_URI and it should work fine. I'll add an example file as well.

**Comment by 1ntroduc3** [comment]
Thanks @jessejputnam . I get this when I have no quotes:
`node app.js
express-session deprecated req.secret; provide secret option app.js:84:3
(node:30120) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\connection.js:695
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
          ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at Connection.openUri (C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\connection.js:695:11)
    at C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\index.js:414:10
    at C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\index.js:1290:10)
    at Mongoose.connect (C:\Users\marth\Downloads\card-collector-main\node_modules\mongoose\lib\index.js:413:20)
    at Object.<anonymous> (C:\Users\marth\Downloads\card-collector-main\app.js:22:10)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)

Node.js v20.9.0
PS C:\Users\marth\Downloads\card-collector-main>`

**Comment by jessejputnam** [comment]
Do you have your .env file at the same root as app.js?
<img width="213" alt="Screenshot 2024-03-31 at 10 39 33 AM" src="https://github.com/jessejputnam/card-collector/assets/66268183/bc2f82bc-d95f-4a4e-84d2-edb44ef9720f">

**Comment by 1ntroduc3** [comment]
Yes it is, now it's working!! Only thing is I can not add 197/091 PAF card pidgeotto 

`Card validation failed: meta.rarity.grade: Path `meta.rarity.grade` is required.`

thanks for great tool!

**Comment by jessejputnam** [comment]
Alright! Just added the new rarity value, "Shiny Rare". So you should be able to add that card no problem now!

**Comment by 1ntroduc3** [comment]
Thank you!
